---
namespace: nephelaiio
name: consul
version: 0.2.2
readme: README.md
authors:
  - Ted Cook <358176+teddyphreak@users.noreply.github.com>
description: your collection description
license:
  - MIT
tags:
  - consul
dependencies:
  "nephelaiio.plugins": "*"
repository: http://github.com/nephelaiio/ansible-collection-consul
documentation: http://github.com/nephelaiio/ansible-collection-consul
homepage: http://github.com/nephelaiio/ansible-collection-consul
issues: http://github.com/nephelaiio/ansible-collection-consul/issues
build_ignore:
  - .devbox
  - .venv
