---
- name: Prepare Consul stack members
  hosts: "{{ _consul_hostgroup }}"
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Install yum prerequisites
      ansible.builtin.package:
        name:
          - acl
          - cronie
          - yum-utils
          - python3-dnf-plugin-versionlock
      when: ansible_os_family == 'RedHat'

    - name: Install apt prerequisites
      ansible.builtin.package:
        name:
          - acl
          - cron
          - gpg-agent
      when: ansible_os_family == 'Debian'
