---
- name: Prepare Consul stack members
  hosts: "{{ _consul_hostgroup }}"
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Add host entries for cluster members
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ item }}.*"
        line: "{{ _member_address }} {{ _fqdn }} {{ _hostname }}"
      vars:
        _member_address: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
        _fqdn: "{{ hostvars[item]['ansible_fqdn'] }}"
        _hostname: "{{ hostvars[item]['ansible_hostname'] }}"
      loop: "{{ ansible_play_hosts }}"
      when: _consul_config_hostnames

    - name: Install yum prerequisites
      ansible.builtin.package:
        name:
          - acl
          - cronie
          - yum-utils
          - python3-dnf-plugin-versionlock
      when: ansible_os_family == 'RedHat'

    - name: Install apt prerequisites
      ansible.builtin.package:
        name:
          - acl
          - cron
      when: ansible_os_family == 'Debian'
