---
name: libvirt

on:
  pull_request:
    branches:
      - master
    paths:
      - "playbooks/prepare.yml"
      - "molecule/update/*.yml"
      - "playbooks/update.yml"
      - ".github/workflows/libvirt.yml"

defaults:
  run:
    working-directory: "nephelaiio.consul"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  libvirt:
    name: libvirt
    runs-on: libvirt
    needs: version
    strategy:
      matrix:
        scenario:
          - update
        image:
          - noble
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "nephelaiio.consul"

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          project-path: "nephelaiio.consul"
          enable-cache: true

      - name: Run molecule tests
        run: devbox run -- make ${{ matrix.image }} test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_KVM_IMAGE: ${{ matrix.image }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
