---
name: lint

defaults:
  run:
    working-directory: "nephelaiio.consul"

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "nephelaiio.consul"

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          project-path: "nephelaiio.consul"
          enable-cache: true

      - name: Lint code
        run: devbox run -- make lint
